services:
  - type: web
    name: data-cleaning-agent-fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn scripts.backend:app  --host 0.0.0.0 --port 8000"
    pythonVersion: 3.10
